path = "/Users/ai_stina/harvest/harvest.py"
with open(path) as f:
    lines = f.readlines()

new_func = [
    "def scrape_product(store, url):\n",
    '    """Ett pass via CF_SCRAPER + JS. Snabbare/billigare an AI_SCRAPER.\n',
    "    Klarar kicks.se Cloudflare via proxy-rotation. BESLUT-SS-075.\"\"\"\n",
    "    js = (\n",
    "        \"const ld=Array.from(document.querySelectorAll('script')).filter(\"\n",
    "        \"function(s){return s.type==='application/ld+json';}).map(\"\n",
    "        \"function(s){try{return JSON.parse(s.textContent);}catch(e){return {};}});\"\n",
    "        \"const prod=ld.find(function(d){return d['@type']==='Product';})||{};\"\n",
    "        \"const offer=(prod.offers&&prod.offers[0])||prod.offers||{};\"\n",
    "        \"const h1=document.querySelector('h1');\"\n",
    "        \"const name=prod.name||(h1?h1.innerText.trim():null);\"\n",
    "        \"const brand=(prod.brand&&prod.brand.name)||null;\"\n",
    "        \"const price=offer.price||null;\"\n",
    "        \"const allLd=ld.map(function(d){return JSON.stringify(d);}).join(' ');\"\n",
    "        \"const ean=prod.gtin13||prod.gtin||(allLd.match(/\\\\b(\\\\d{13})\\\\b/)||[])[1]||null;\"\n",
    "        \"const imgMeta=document.querySelector('meta[property=\\\"og:image\\\"]');\"\n",
    "        \"const image=imgMeta?imgMeta.getAttribute('content'):(prod.image||null);\"\n",
    "        \"function sc(t){if(!t)return 0;\"\n",
    "        \"var c=(t.match(/,/g)||[]).length;\"\n",
    "        \"var h=/\\\\b(aqua|water|glycerin|parfum|fragrance|alcohol|sodium)\\\\b/i.test(t);\"\n",
    "        \"return(c>=4&&h)?c:0;}\"\n",
    "        \"var inci=null,best=0;\"\n",
    "        \"document.querySelectorAll('p,div,span,li').forEach(function(el){\"\n",
    "        \"var t=(el.innerText||'').trim();\"\n",
    "        \"if(t.length<20||t.length>4000)return;\"\n",
    "        \"var s=sc(t);if(s>best){best=s;inci=t;}});\"\n",
    "        \"return JSON.stringify({name:name,brand:brand,price:price,ean:ean,\"\n",
    "        \"image:image,inci:inci});\"\n",
    "    )\n",
    "    payload = {\n",
    '        "urls": [url],\n',
    '        "page_is_loaded_before_running_script": True,\n',
    '        "retrieve_result_from_js_script": True,\n',
    '        "execute_js_async": False,\n',
    '        "retrieve_html_from_url_after_loaded": False,\n',
    '        "js_timeout": 20,\n',
    '        "max_retries_per_url": 2,\n',
    '        "js_script": js,\n',
    '        "proxy": {"useApifyProxy": True},\n',
    "    }\n",
    "    try:\n",
    "        items = _run_apify(CF_SCRAPER, payload)\n",
    '        data = json.loads(items[0]["result_from_js_script"])\n',
    "    except Exception as e:\n",
    '        print(f"  ! scrape_product misslyckades for {url}: {e}", file=sys.stderr)\n',
    "        return None\n",
    '    if not data.get("name"):\n',
    "        return None\n",
    '    inci = data.get("inci")\n',
    '    if not inci and data.get("ean"):\n',
    '        inci = obf_ingredients(data["ean"])\n',
    "    return {\n",
    '        "source_store": store,\n',
    '        "source_url": url,\n',
    '        "brand": data.get("brand"),\n',
    '        "product_name": data.get("name"),\n',
    '        "category": None,\n',
    '        "price": data.get("price"),\n',
    '        "currency": "SEK",\n',
    '        "quantity": None,\n',
    '        "ingredients_raw": inci,\n',
    '        "barcode": data.get("ean"),\n',
    '        "image_url": data.get("image"),\n',
    "    }\n",
    "\n",
]

lines[106:157] = new_func
with open(path, "w") as f:
    f.writelines(lines)
print("OK - " + str(len(new_func)) + " rader inskrivna")
