import { Router, type IRouter } from "express";
import healthRouter from "./health";
import analyzeRouter from "./analyze";
import analyzeSingleRouter from "./analyze-single";
import scanLabelRouter from "./scan-label";
import productLookupRouter from "./product-lookup";
import suggestAlternativesRouter from "./suggest-alternatives";
import authRouter from "./auth";
import shelfRouter from "./shelf";
import chatRouter from "./chat";
import barcodeLookupRouter from "./barcode-lookup";
import statsRouter from "./stats";
import paymentsRouter from "./payments";
import analysisCacheRouter from "./analysis-cache";
import contributeRouter from "./contribute";
import storageRouter from "./storage";
import recipesRouter from "./recipes";
import productsRouter from "./products";
import leaderboardRouter from "./leaderboard";
import tipsRouter from "./tips";
import discoverRatingsRouter from "./discover-ratings";
import ingredientsRouter from "./ingredients";
import adminUsersRouter from "./admin-users";
import adminTesterPromoRouter from "./admin-tester-promo";
import feedbackRouter from "./feedback";
import scanEventsRouter from "./scan-events";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(analyzeRouter);
router.use(analyzeSingleRouter);
router.use(scanLabelRouter);
router.use(productLookupRouter);
router.use(suggestAlternativesRouter);
router.use(shelfRouter);
router.use(chatRouter);
router.use(barcodeLookupRouter);
router.use(statsRouter);
router.use(paymentsRouter);
router.use(analysisCacheRouter);
router.use(contributeRouter);
router.use(storageRouter);
router.use(recipesRouter);
router.use(productsRouter);
router.use(leaderboardRouter);
router.use(tipsRouter);
router.use(discoverRatingsRouter);
router.use(ingredientsRouter);
router.use(adminUsersRouter);
router.use(adminTesterPromoRouter);
router.use(feedbackRouter);
router.use(scanEventsRouter);

export default router;
