import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import analyzeRouter from "./analyze.js";
import analyzeSingleRouter from "./analyze-single.js";
import scanLabelRouter from "./scan-label.js";
import scanProductNameRouter from "./scan-product-name.js";
import productLookupRouter from "./product-lookup.js";
import suggestAlternativesRouter from "./suggest-alternatives.js";
import authRouter from "./auth.js";
import shelfRouter from "./shelf.js";
import chatRouter from "./chat.js";
import barcodeLookupRouter from "./barcode-lookup.js";
import statsRouter from "./stats.js";
import paymentsRouter from "./payments.js";
import analysisCacheRouter from "./analysis-cache.js";
import contributeRouter from "./contribute.js";
import storageRouter from "./storage.js";
import recipesRouter from "./recipes.js";
import productsRouter from "./products.js";
import leaderboardRouter from "./leaderboard.js";
import tipsRouter from "./tips.js";
import discoverRatingsRouter from "./discover-ratings.js";
import ingredientsRouter from "./ingredients.js";
import adminUsersRouter from "./admin-users.js";
import adminTesterPromoRouter from "./admin-tester-promo.js";
import feedbackRouter from "./feedback.js";
import scanEventsRouter from "./scan-events.js";
import adminFunnelRouter from "./admin-funnel.js";
import checkoutAbandonmentRouter from "./checkout-abandonment.js";
import checkoutRecoveryRouter from "./checkout-recovery.js";
import recallsRouter from "./recalls.js";
import profileOnboardingRouter from "./profile-onboarding.js";
import profileRouter from "./profile.js";
import reportRouter from "./report.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(analyzeRouter);
router.use(analyzeSingleRouter);
router.use(scanLabelRouter);
router.use(scanProductNameRouter);
router.use(productLookupRouter);
router.use(suggestAlternativesRouter);
router.use(shelfRouter);
router.use(chatRouter);
router.use(barcodeLookupRouter);
router.use(statsRouter);
router.use(paymentsRouter);
router.use(analysisCacheRouter);
router.use(contributeRouter);
router.use(storageRouter);
router.use(recipesRouter);
router.use(productsRouter);
router.use(leaderboardRouter);
router.use(tipsRouter);
router.use(discoverRatingsRouter);
router.use(ingredientsRouter);
router.use(adminUsersRouter);
router.use(adminTesterPromoRouter);
router.use(feedbackRouter);
router.use(scanEventsRouter);
router.use(adminFunnelRouter);
router.use(checkoutAbandonmentRouter);
router.use(checkoutRecoveryRouter);
router.use(recallsRouter);
router.use(profileOnboardingRouter);
router.use(profileRouter);
router.use(reportRouter);

export default router;
