// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ArchitectureDiagram.tsx": () => import("../components/mockups/ArchitectureDiagram.tsx"),
  "./components/mockups/LeanCanvas.tsx": () => import("../components/mockups/LeanCanvas.tsx")
};
