export const DEMO = {
  productFull: {
    name: "CeraVe Hydrating Cream",
    brand: "CeraVe",
    barcode: "3337875597203",
    rating: 4.3,
    ratingCount: 218,
    image: "🧴",
    verdict: "safe" as const,
    headline: "Looks safe for your routine",
    subhead: "No harmful conflicts found across the 14 ingredients we checked.",
    ingredients: [
      "Aqua",
      "Glycerin",
      "Cetearyl Alcohol",
      "Caprylic/Capric Triglyceride",
      "Ceramide NP",
      "Hyaluronic Acid",
      "Niacinamide",
      "Phenoxyethanol",
      "Tocopherol",
      "Cholesterol",
      "Phytosphingosine",
      "Carbomer",
      "Sodium Hyaluronate",
      "Disodium EDTA",
    ],
    flags: [],
  },
  productPartial: {
    name: "Ordinary Retinol 1%",
    brand: "The Ordinary",
    barcode: "769915190892",
    image: "💧",
    verdict: "warning" as const,
    headline: "Conflict with your morning routine",
    subhead:
      "Retinol shouldn't be combined with your AHA toner. Use them on alternating evenings.",
    ingredients: [
      "Squalane",
      "Caprylic/Capric Triglyceride",
      "Retinol 1%",
      "BHT",
      "Tocopherol",
    ],
    flags: ["Photosensitiser", "Pregnancy caution"],
    missing: ["productPhoto", "rating"] as const,
  },
  productMissing: {
    barcode: "7311070042815",
    queryName: "Lumene Nordic-C [Valo] Glow Boost Essence",
    image: "❓",
  },
  recent: [
    { name: "CeraVe Foaming Cleanser", verdict: "safe" as const, when: "today" },
    { name: "Paula's Choice 2% BHA", verdict: "warning" as const, when: "yesterday" },
    { name: "La Roche-Posay Cicaplast B5", verdict: "safe" as const, when: "Mon" },
    { name: "Drunk Elephant T.L.C. Sukari", verdict: "warning" as const, when: "Sun" },
  ],
};
